### ISSUE TITLE
Phantomjs error: TypeError: undefined is not an object (evaluating 'phantomArgs.forEach')

### ISSUE THREAD

**Issue by alexserver** [nathanboktae/mocha-casperjs#80] opened 2016-02-09 19:14 UTC
I'm getting the following error when I attempt to run tests:
```
> mocha-casperjs --ignore-ssl-errors=yes ./tests/**/*.js

Fontconfig warning: ignoring UTF-8: not a valid region tag
TypeError: undefined is not an object (evaluating 'phantomArgs.forEach')

  phantomjs://platform/cli.js:103 in parse
```

I'm running from my project
`npm run test`

In scripts I have configured:
`"test": "mocha-casperjs --ignore-ssl-errors=yes ./tests/**/*.js",`

I have globally installed:
`phantomjs@2.1.3`

And locally installed:
```
    "casper-chai": "^0.2.1",
    "casperjs": "^1.1.0-beta4",
    "chai": "^3.5.0",
    "mocha": "^2.3.4",
    "mocha-casperjs": "^0.5.5"
```

**Comment by nathanboktae** [comment] 2016-02-11 01:50
`mocha-casperjs` doesn't take in wildcards and doesn't support pulling all files in a directory (see #20), so you need to specify things individually.

As for the error, it uses casperjs' internal argument parsing, so you probably hit a bug there.

**Comment by alexserver** [comment] 2016-02-11 05:11
@nathanboktae `./tests/**/*.js` is using glob syntax.

So, mocha let me executes a list of tests files within many directories, what do you recommend me for this ?

Oh ! and I forgot to mention !
when I had phantomjs@1.9.x and casperjs@1.1.0-beta3 this was working good, but I had to upgrade to phantomjs@2.x because of DOM libraries (I'm using Ractive.js but that's another story).

**Comment by nathanboktae** [comment] 2016-02-11 05:40
> @nathanboktae ./tests/**/*.js is using glob syntax.

Er yeah that's what I meant by wildcards. I'm still unlearning Microspeak.

> what do you recommend me for this ?

Since you have to specify each file individually now, some shell magic or other means to enumerate the files then list them out is what you want, like

    mocha-casperjs --ignore-ssl-errors=yes `ls ./tests/**/*.js`

or  `zsh` does glob completion for you when pressing tab. not sure if that works with npm scripts.

or fix #20 and send a PR ;)

**Comment by alexserver** [comment] 2016-02-11 19:48
@nathanboktae this problem is not caused by the glob syntax.
Even if I run one file, this crashed with phantom 2.x
It works great with 1.9.x but not with 2.x

I tracked the error is happening in the module casperjs, /modules/cli.js line 101, phantomArgs is being passed as undefined object.

https://github.com/n1k0/casperjs/blob/master/modules/cli.js#L102

Can you or someone with more experience about this libraries help me ?

**Comment by alexserver** [comment] 2016-02-11 20:00
@nathanboktae this is not this package's problem, I found a way out here:
https://github.com/n1k0/casperjs/issues/1150

thanks.

**Comment by nathanboktae** [comment] 2016-02-11 20:01
> It works great with 1.9.x but not with 2.x

1.1-beta3 does not support phantomjs 2, as you found out. Only recently did it get phantomjs 2 support, yes. n1k0/casperjs#1352

**Comment by istr** [comment] 2016-02-12 08:38
The best advice we can give at the moment is: stop using a cli wrapper for CasperJS integration.

We will try to fix the ```cli``` as best as we can, but we will certainly not roll back the non-cli changes that simplified PhantomJS integration to work for all versions without explicit version checks.

**Comment by istr** [comment] 2016-02-12 08:47
The problem you have is the "naive" call ```cliOptions = cli.parse(phantom.args)``` in https://github.com/nathanboktae/mocha-casperjs/blob/master/bin/cli.js#L2.

I bet that if you change this along the lines of https://github.com/n1k0/casperjs/blob/master/bin/bootstrap.js#L92 to

 ```js
cliOptions = cli.parse(require('system').args)
```

this should work for PhantomJS 1.9.x and 2.* and SlimerJS.

**Comment by nathanboktae** [comment] 2016-02-12 16:37
Thanks @istr I didn't know that was deprecated - I'll move to using `require('system').args`

**Comment by nathanboktae** [comment] 2016-02-12 17:34
> The best advice we can give at the moment is: stop using a cli wrapper for CasperJS integration.

Glad to see you guys and others picking up the torch and pushing casperjs forward after the long haitus. One thing @n1k0 mentioned a long time ago was [separating out the automation pieces from the test pieces](https://github.com/n1k0/casperjs/issues/278#issuecomment-27285765) - if there was a plugin mechanism to bring your own test framework, `mocha-casperjs` could just turn into that.

casperjs' patched `require` and phantomjs' lack of `require.paths` support (at the time, dunno about 2.x) caused me a lot of grief so the `cli` wrapper is to address issues with that. Believe me I'd rather not do a `cli` wrapper and just focus on gluing mocha + casper together.

**Comment by alexserver** [comment] 2016-02-12 18:44
thanks to @ist for clarify the situation and spot the actual problem.
thanks to @nathanboktae for fixing it and releasing a new version.
As a software libraries user, I found both packages (casperjs and mocha-casperjs) very helpful for my daily work, I bet I'm not the only one that will be benefit with this.

**Comment by istr** [comment] 2016-02-13 10:58
> casperjs' patched require and phantomjs' lack of require.paths support (at the time, dunno about 2.x) caused me a lot of grief so the cli wrapper is to address issues with that.

Ok, thanks for pointing that out -- will keep it in mind for the next steps.

**Comment by dschinkel** [comment] 2016-02-18 04:38
So was this fixed? I have the same issue.

**Comment by nathanboktae** [comment] 2016-02-18 06:17
I can't reproduce this actually:

```
~/github/mocha-casperjs-copy 2921cd2|master ✔
10:10PM ᐅ npm install -g mocha-casperjs
npm WARN peerDependencies The peer dependency mocha@>= 1.14.0 included from mocha-casperjs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency casperjs@>= 1.1.0-beta3 included from mocha-casperjs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/Users/nblack/.nvm/versions/node/v4.2.1/bin/mocha-casperjs -> /Users/nblack/.nvm/versions/node/v4.2.1/lib/node_modules/mocha-casperjs/bin/mocha-casperjs
/Users/nblack/.nvm/versions/node/v4.2.1/bin/casperjs -> /Users/nblack/.nvm/versions/node/v4.2.1/lib/node_modules/casperjs/bin/casperjs
casperjs@1.1.0-beta5 /Users/nblack/.nvm/versions/node/v4.2.1/lib/node_modules/casperjs

mocha-casperjs@0.5.5 /Users/nblack/.nvm/versions/node/v4.2.1/lib/node_modules/mocha-casperjs


~/github/mocha-casperjs-copy 2921cd2|master ✔
10:13PM ᐅ mocha-casperjs --ignore-ssl-errors=yes test/temptest.js


  in casperjs
    1) the test


  0 passing (5s)
  1 failing

  1) in casperjs the test:
     "h1" still did not exist 5000ms



~/github/mocha-casperjs-copy 2921cd2|master ✔
10:14PM ᐅ phantomjs --version
1.9.8
```

What phantomjs version are you using?

**Comment by dschinkel** [comment] 2016-02-18 13:49
I don't know but I am getting it with Phantom 2.1.1 installed

**Comment by dschinkel** [comment] 2016-02-18 13:50
I thought the fix was something you were going to work on nathan??  reading the above due to the PhantomJS 2.0 situation

**Comment by nathanboktae** [comment] 2016-02-18 17:52
> I don't know but I am getting it with Phantom 2.1.1 installed

Ah yes, I'll give it a shot with that. I should add it as a test target in travis too.

**Comment by dschinkel** [comment] 2016-02-18 19:52
If you don't mind I want to fork it and put in the fix is that ok?

**Comment by dschinkel** [comment] 2016-02-18 20:57
I just forked it and will submit the fix today...nice job on the tests Nathan

**Comment by nathanboktae** [comment] 2016-03-25 19:01
Closing since #85 was accepted

**Closed by nathanboktae** 2016-03-25 19:01 UTC
